version: '3.8'

services:
  backend:
    build:
      context: ./backend
    environment:
      - DB_HOST=database
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=vigisec
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vigisec
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data:
