version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: vigisec_user
      POSTGRES_PASSWORD: vigisec_password
      POSTGRES_DB: vigisec_db
    ports:
      - "5432:5432"

  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: bash -c "npm install && npm start"
    ports:
      - "3000:3000"
